# Generated by Django 4.1 on 2023-05-07 14:21

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название лотереи')),
            ],
        ),
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2023, 5, 7), verbose_name='Дата розыгрыша')),
                ('price', models.IntegerField(verbose_name='Цена билета')),
                ('result', models.IntegerField(default=0, verbose_name='Сумма выигрыша')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='enterstat.name')),
            ],
        ),
    ]
