# Generated by Django 4.1 on 2023-05-07 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterstat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='name',
            name='jackpot',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
